server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employees?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test@123
# 开启mybatis的debug日志
logging:
  level:
    com:
      sununiq: debug
ybatis:
  enable: true
  domain-locations: com.sununiq.domain
  output-location: target/mapper-output